import {
  Truck,
  FileText,
  DollarSign,
  Clock,
  Award,
  Users,
  Shield,
  Building2,
  MapPin,
  User,
  Briefcase,
  Heart,
  Flame,
  BookOpen,
  Utensils,
  Tent,
  Camera,
  Package,
  Calendar,
  Car,
} from "lucide-react";

export type TooltipType = "success" | "error" | "info" | "";
export interface TooltipState {
  show: boolean;
  message: string;
  type: TooltipType;
}

export interface VendorFormData {
  [key: string]: string | boolean | number;
}

export interface VendorField {
  name: string;
  label: string;
  type:
    | "text"
    | "number"
    | "textarea"
    | "checkbox"
    | "select"
    | "email"
    | "tel"
    | "date"
    | "file"
    | "time";
  placeholder?: string;
  options?: string[];
  required?: boolean;
  step?: number;
  accept?: string;
}

export interface VendorCategory {
  id: string;
  name: string;
  icon?: any;
  fields: VendorField[];
}

export const commonStep1Fields: VendorField[] = [
  {
    name: "fullName",
    label: "Full Name",
    type: "text",
    placeholder: "Enter your full name",
    required: true,
    step: 1,
  },
  {
    name: "email",
    label: "Email Address",
    type: "email",
    placeholder: "your@email.com",
    required: true,
    step: 1,
  },
  {
    name: "phone",
    label: "Mobile Number",
    type: "tel",
    placeholder: "9876543210",
    required: true,
    step: 1,
  },
  {
    name: "alternatePhone",
    label: "Alternate Number",
    type: "tel",
    placeholder: "Optional",
    required: false,
    step: 1,
  },
  {
    name: "city",
    label: "City",
    type: "text",
    placeholder: "Mumbai",
    required: true,
    step: 1,
  },
  {
    name: "state",
    label: "State",
    type: "text",
    placeholder: "Maharashtra",
    required: true,
    step: 1,
  },
  {
    name: "address",
    label: "Address",
    type: "textarea",
    placeholder: "Full address with landmark",
    required: true,
    step: 1,
  },
  {
    name: "pincode",
    label: "Pincode",
    type: "number",
    placeholder: "400001",
    required: true,
    step: 1,
  },
  {
    name: "aadharCard",
    label: "Aadhar Card",
    type: "file",
    accept: ".pdf,.jpg,.png",
    required: true,
    step: 1,
  },
  {
    name: "panCard",
    label: "PAN Card",
    type: "file",
    accept: ".pdf,.jpg,.png",
    required: true,
    step: 1,
  },
];

export const vendorCategories: VendorCategory[] = [
  {
    id: "pandit_purohit",
    name: "Pandit / Purohit",
    icon: User,
    fields: [
      {
        name: "priestName",
        label: "Full Name",
        type: "text",
        placeholder: "Pandit Name",
        required: true,
        step: 2,
      },
      {
        name: "experience",
        label: "Years of Experience",
        type: "number",
        placeholder: "15",
        required: true,
        step: 2,
      },
      {
        name: "specialization",
        label: "Specialization",
        type: "textarea",
        placeholder:
          "Antim Sanskar, Shradh, Tehravin, Pind Daan, Narayan Bali, Garud Puran Path",
        required: true,
        step: 2,
      },
      {
        name: "languages",
        label: "Languages Known",
        type: "text",
        placeholder: "Hindi, Sanskrit, English, Marathi, Gujarati",
        required: true,
        step: 2,
      },
      {
        name: "qualifications",
        label: "Qualifications",
        type: "text",
        placeholder: "Acharya, Shastri, Vedic Scholar",
        step: 2,
      },
      {
        name: "gotra",
        label: "Gotra",
        type: "text",
        placeholder: "Your Gotra (optional)",
        step: 2,
      },
      {
        name: "antimSanskar",
        label: "Antim Sanskar (Cremation Rituals)",
        type: "checkbox",
        step: 3,
      },
      {
        name: "shradhCeremony",
        label: "Shradh/Teravin Ceremony",
        type: "checkbox",
        step: 3,
      },
      {
        name: "pindDaan",
        label: "Pind Daan",
        type: "checkbox",
        step: 3,
      },
      {
        name: "asthiVisarjan",
        label: "Asthi Visarjan",
        type: "checkbox",
        step: 3,
      },
      {
        name: "garudPuran",
        label: "Garud Puran Path",
        type: "checkbox",
        step: 3,
      },
      {
        name: "narayanBali",
        label: "Narayan Bali",
        type: "checkbox",
        step: 3,
      },
      {
        name: "tehravin",
        label: "Tehravin/Tervi",
        type: "checkbox",
        step: 3,
      },
      {
        name: "barsi",
        label: "Barsi (Death Anniversary)",
        type: "checkbox",
        step: 3,
      },
      {
        name: "serviceArea",
        label: "Service Area",
        type: "textarea",
        placeholder: "Cities/Locations you serve",
        required: true,
        step: 4,
      },
      {
        name: "availability247",
        label: "24x7 Available",
        type: "checkbox",
        step: 4,
      },
      {
        name: "travelAllowed",
        label: "Travel to Location",
        type: "checkbox",
        step: 4,
      },
      {
        name: "travelLimit",
        label: "Travel Limit (km)",
        type: "number",
        placeholder: "50",
        step: 4,
      },
      {
        name: "advanceBooking",
        label: "Advance Booking Required",
        type: "select",
        options: ["Same Day", "1 Day Before", "3 Days Before", "1 Week Before"],
        step: 4,
      },
      {
        name: "basicCeremony",
        label: "Basic Ceremony Charges",
        type: "number",
        placeholder: "1100",
        required: true,
        step: 5,
      },
      {
        name: "fullCeremony",
        label: "Complete Ceremony Charges",
        type: "number",
        placeholder: "2100",
        step: 5,
      },
      {
        name: "travelCharges",
        label: "Travel Charges (Extra)",
        type: "number",
        placeholder: "300",
        step: 5,
      },
    ],
  },

  // 2. AMBULANCE PROVIDER
  {
    id: "ambulance_service",
    name: "Ambulance ",
    icon: Truck,
    fields: [
      {
        name: "vehicleNumber",
        label: "Vehicle Registration Number",
        type: "text",
        placeholder: "MH01AB1234",
        required: true,
        step: 2,
      },
      {
        name: "ambulanceType",
        label: "Ambulance Type",
        type: "select",
        options: [
          "Basic Life Support (BLS)",
          "Advanced Life Support (ALS)",
          "Patient Transport Vehicle",
          "Mortuary Ambulance",
          "Dead Body Carrier",
        ],
        required: true,
        step: 2,
      },
      {
        name: "vehicleModel",
        label: "Vehicle Make/Model",
        type: "text",
        placeholder: "Toyota HiAce / Tata Winger",
        required: true,
        step: 2,
      },
      {
        name: "manufactureYear",
        label: "Manufacture Year",
        type: "number",
        placeholder: "2022",
        required: true,
        step: 2,
      },
      {
        name: "fleetSize",
        label: "Total Fleet Size",
        type: "number",
        placeholder: "3",
        required: true,
        step: 2,
      },
      {
        name: "oxygenCylinder",
        label: "Oxygen Cylinder Available",
        type: "checkbox",
        step: 3,
      },
      {
        name: "ventilator",
        label: "Ventilator Available",
        type: "checkbox",
        step: 3,
      },
      {
        name: "defibrillator",
        label: "Defibrillator Available",
        type: "checkbox",
        step: 3,
      },
      {
        name: "stretcher",
        label: "Stretcher Available",
        type: "checkbox",
        step: 3,
      },
      {
        name: "firstAid",
        label: "First Aid Kit",
        type: "checkbox",
        step: 3,
      },
      {
        name: "deadBodyBox",
        label: "Dead Body Box/Carrier",
        type: "checkbox",
        step: 3,
      },
      {
        name: "additionalEquipment",
        label: "Additional Equipment",
        type: "textarea",
        placeholder: "List any other medical equipment available",
        step: 3,
      },
      {
        name: "serviceArea",
        label: "Service Area (Cities/Radius in km)",
        type: "text",
        placeholder: "Mumbai, Thane, Navi Mumbai - 50km radius",
        required: true,
        step: 4,
      },
      {
        name: "responseTime",
        label: "Average Response Time",
        type: "select",
        options: [
          "Within 15 mins",
          "Within 30 mins",
          "Within 45 mins",
          "Within 60 mins",
        ],
        required: true,
        step: 4,
      },
      {
        name: "availability247",
        label: "24x7 Availability",
        type: "checkbox",
        required: true,
        step: 4,
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact Number",
        type: "tel",
        placeholder: "9876543210",
        required: true,
        step: 4,
      },
      {
        name: "driverCount",
        label: "Number of Drivers",
        type: "number",
        placeholder: "5",
        required: true,
        step: 4,
      },
      {
        name: "staffCount",
        label: "Number of Attendants",
        type: "number",
        placeholder: "6",
        step: 4,
      },
      {
        name: "localCharges",
        label: "Local Charges (Within City)",
        type: "number",
        placeholder: "1500",
        required: true,
        step: 5,
      },
      {
        name: "outstationCharges",
        label: "Outstation Charges (Per km)",
        type: "number",
        placeholder: "25",
        step: 5,
      },
      {
        name: "waitingCharges",
        label: "Waiting Charges (Per hour)",
        type: "number",
        placeholder: "200",
        step: 5,
      },
      {
        name: "nightCharges",
        label: "Night Charges (10 PM - 6 AM)",
        type: "number",
        placeholder: "500",
        step: 5,
      },
      {
        name: "deadBodyCharges",
        label: "Dead Body Transport Charges",
        type: "number",
        placeholder: "2500",
        step: 5,
      },
      {
        name: "transportLicense",
        label: "Transport Department License",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
      {
        name: "insuranceCertificate",
        label: "Vehicle Insurance Certificate",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
      {
        name: "pollutionCertificate",
        label: "Pollution Under Control Certificate",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
      {
        name: "driverLicense",
        label: "Driver's License Copies",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
    ],
  },

  // 3. HEARSE VAN / DEAD BODY TRANSPORT PROVIDER
  {
    id: "body_transport",
    name: "Hearse Van / Dead Body Transport",
    icon: Car,
    fields: [
      {
        name: "vehicleNumber",
        label: "Van Registration Number",
        type: "text",
        placeholder: "MH02CD5678",
        required: true,
        step: 2,
      },
      {
        name: "vanModel",
        label: "Van Make/Model",
        type: "text",
        placeholder: "Toyota HiAce / Force Traveller",
        required: true,
        step: 2,
      },
      {
        name: "manufactureYear",
        label: "Manufacture Year",
        type: "number",
        placeholder: "2021",
        required: true,
        step: 2,
      },
      {
        name: "vanType",
        label: "Van Type",
        type: "select",
        options: ["Standard", "Premium", "Luxury", "Economy", "AC", "Non-AC"],
        required: true,
        step: 2,
      },
      {
        name: "vanColor",
        label: "Van Color",
        type: "text",
        placeholder: "White/Black/Silver",
        step: 2,
      },
      {
        name: "fleetSize",
        label: "Total Fleet Size",
        type: "number",
        placeholder: "2",
        step: 2,
      },
      {
        name: "acAvailable",
        label: "Air Conditioned",
        type: "checkbox",
        step: 3,
      },
      {
        name: "decorAvailable",
        label: "Decoration Available",
        type: "checkbox",
        step: 3,
      },
      {
        name: "flowerArrangement",
        label: "Flower Arrangement",
        type: "checkbox",
        step: 3,
      },
      {
        name: "ledDisplay",
        label: "LED Display Available",
        type: "checkbox",
        step: 3,
      },
      {
        name: "soundSystem",
        label: "Sound System",
        type: "checkbox",
        step: 3,
      },
      {
        name: "coolingBox",
        label: "Built-in Cooling Box",
        type: "checkbox",
        step: 3,
      },
      {
        name: "stretcherType",
        label: "Stretcher Type",
        type: "select",
        options: ["Manual", "Hydraulic", "Electric", "Standard"],
        step: 3,
      },
      {
        name: "serviceArea",
        label: "Service Area",
        type: "textarea",
        placeholder: "Cities/Locations served",
        required: true,
        step: 4,
      },
      {
        name: "availability247",
        label: "24x7 Availability",
        type: "checkbox",
        required: true,
        step: 4,
      },
      {
        name: "driverExperience",
        label: "Driver Experience (years)",
        type: "number",
        placeholder: "5",
        required: true,
        step: 4,
      },
      {
        name: "attendantAvailable",
        label: "Attendant Available",
        type: "checkbox",
        step: 4,
      },
      {
        name: "localCharges",
        label: "Local Charges (Within City)",
        type: "number",
        placeholder: "2000",
        required: true,
        step: 5,
      },
      {
        name: "outstationCharges",
        label: "Outstation Charges (Per km)",
        type: "number",
        placeholder: "30",
        step: 5,
      },
      {
        name: "acCharges",
        label: "AC Charges (Extra)",
        type: "number",
        placeholder: "500",
        step: 5,
      },
      {
        name: "decorationCharges",
        label: "Decoration Charges",
        type: "number",
        placeholder: "1000",
        step: 5,
      },
      {
        name: "permitNumber",
        label: "Transport Permit Number",
        type: "text",
        placeholder: "MH/TRAN/2025/789",
        required: true,
        step: 6,
      },
      {
        name: "insuranceValid",
        label: "Insurance Valid Till",
        type: "date",
        required: true,
        step: 6,
      },
      {
        name: "fitnessCertificate",
        label: "Vehicle Fitness Certificate",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
    ],
  },

  // 4. FREEZER BOX PROVIDER
  {
    id: "freezer_box",
    name: "Freezer Box ",
    icon: Building2,
    fields: [
      {
        name: "totalBoxes",
        label: "Total Freezer Boxes Available",
        type: "number",
        placeholder: "15",
        required: true,
        step: 2,
      },
      {
        name: "availableNow",
        label: "Currently Available",
        type: "number",
        placeholder: "8",
        required: true,
        step: 2,
      },
      {
        name: "boxSizes",
        label: "Box Sizes Available",
        type: "text",
        placeholder: "6ft, 6.5ft, 7ft, 7.5ft",
        required: true,
        step: 2,
      },
      {
        name: "boxTypes",
        label: "Box Types",
        type: "select",
        options: [
          "Standard",
          "Premium",
          "Heavy Duty",
          "Portable",
          "Industrial",
        ],
        required: true,
        step: 2,
      },
      {
        name: "temperatureRange",
        label: "Temperature Range",
        type: "text",
        placeholder: "-20°C to 0°C",
        required: true,
        step: 2,
      },
      {
        name: "brand",
        label: "Brand/Manufacturer",
        type: "text",
        placeholder: "Blue Star / Voltas / Custom",
        step: 2,
      },
      {
        name: "digitalDisplay",
        label: "Digital Temperature Display",
        type: "checkbox",
        step: 3,
      },
      {
        name: "alarmSystem",
        label: "Temperature Alarm System",
        type: "checkbox",
        step: 3,
      },
      {
        name: "backupBattery",
        label: "Battery Backup",
        type: "checkbox",
        step: 3,
      },
      {
        name: "wheelMount",
        label: "Wheel Mounted",
        type: "checkbox",
        step: 3,
      },
      {
        name: "lockSystem",
        label: "Lock System",
        type: "checkbox",
        step: 3,
      },
      {
        name: "remoteMonitoring",
        label: "Remote Monitoring",
        type: "checkbox",
        step: 3,
      },
      {
        name: "rentalPerDay",
        label: "Rental Price (Per Day)",
        type: "number",
        placeholder: "500",
        required: true,
        step: 4,
      },
      {
        name: "rentalPerWeek",
        label: "Rental Price (Per Week)",
        type: "number",
        placeholder: "3000",
        step: 4,
      },
      {
        name: "rentalPerMonth",
        label: "Rental Price (Per Month)",
        type: "number",
        placeholder: "10000",
        step: 4,
      },
      {
        name: "securityDeposit",
        label: "Security Deposit",
        type: "number",
        placeholder: "2000",
        required: true,
        step: 4,
      },
      {
        name: "deliveryCharges",
        label: "Delivery/Pickup Charges",
        type: "number",
        placeholder: "300",
        step: 4,
      },
      {
        name: "deliveryAvailable",
        label: "Free Delivery Available",
        type: "checkbox",
        step: 5,
      },
      {
        name: "maintenanceService",
        label: "Maintenance Service",
        type: "checkbox",
        step: 5,
      },
      {
        name: "cleaningService",
        label: "Cleaning/Sanitization",
        type: "checkbox",
        step: 5,
      },
      {
        name: "installationService",
        label: "Installation Support",
        type: "checkbox",
        step: 5,
      },
      {
        name: "serviceArea",
        label: "Service/Delivery Area",
        type: "textarea",
        placeholder: "Areas where you provide delivery",
        required: true,
        step: 5,
      },
      {
        name: "availableFrom",
        label: "Available From Date",
        type: "date",
        required: true,
        step: 6,
      },
      {
        name: "operatingHours",
        label: "Operating Hours",
        type: "select",
        options: ["24x7", "6 AM - 10 PM", "8 AM - 8 PM", "9 AM - 6 PM"],
        required: true,
        step: 6,
      },
      {
        name: "emergencyContact",
        label: "Emergency Contact",
        type: "tel",
        placeholder: "9876543210",
        step: 6,
      },
    ],
  },

  // 5. SHAMSHAN GHAT OPERATOR
  {
    id: "shamshan_ghat",
    name: "Shamshan Ghat ",
    icon: MapPin,
    fields: [
      {
        name: "ghatName",
        label: "Shamshan Ghat Name",
        type: "text",
        placeholder: "Name of crematorium",
        required: true,
        step: 2,
      },
      {
        name: "ghatAddress",
        label: "Full Address",
        type: "textarea",
        placeholder: "Location details",
        required: true,
        step: 2,
      },
      {
        name: "totalPlatforms",
        label: "Total Cremation Platforms",
        type: "number",
        placeholder: "6",
        required: true,
        step: 2,
      },
      {
        name: "cremationTypes",
        label: "Cremation Types Offered",
        type: "select",
        options: [
          "Traditional Wood Pyre",
          "Electric Crematorium",
          "Gas Crematorium",
          "Both Electric & Wood",
        ],
        required: true,
        step: 2,
      },
      {
        name: "waitingCapacity",
        label: "Waiting Hall Capacity (People)",
        type: "number",
        placeholder: "100",
        step: 2,
      },
      {
        name: "parkingCapacity",
        label: "Parking Capacity (Vehicles)",
        type: "number",
        placeholder: "50",
        step: 2,
      },
      {
        name: "coldStorage",
        label: "Cold Storage Facility",
        type: "checkbox",
        step: 3,
      },
      {
        name: "coldStorageCapacity",
        label: "Cold Storage Capacity (Bodies)",
        type: "number",
        placeholder: "10",
        step: 3,
      },
      {
        name: "backupGenerator",
        label: "Backup Generator",
        type: "checkbox",
        step: 3,
      },
      {
        name: "waterSupply",
        label: "24x7 Water Supply",
        type: "checkbox",
        step: 3,
      },
      {
        name: "pollutionControl",
        label: "Pollution Control Equipment",
        type: "checkbox",
        step: 3,
      },
      {
        name: "ashCollection",
        label: "Ash Collection System",
        type: "checkbox",
        step: 3,
      },
      {
        name: "priestAvailable",
        label: "Priest/Pandit Available",
        type: "checkbox",
        step: 4,
      },
      {
        name: "poojaSamagri",
        label: "Pooja Samagri Available",
        type: "checkbox",
        step: 4,
      },
      {
        name: "flowerDecoration",
        label: "Flower Decoration",
        type: "checkbox",
        step: 4,
      },
      {
        name: "cateringService",
        label: "Catering Service",
        type: "checkbox",
        step: 4,
      },
      {
        name: "documentationHelp",
        label: "Documentation Assistance",
        type: "checkbox",
        step: 4,
      },
      {
        name: "bookingTiming",
        label: "Booking Timings",
        type: "text",
        placeholder: "6 AM - 8 PM",
        required: true,
        step: 5,
      },
      {
        name: "advanceBooking",
        label: "Advance Booking Available",
        type: "checkbox",
        step: 5,
      },
      {
        name: "onlineBooking",
        label: "Online Booking",
        type: "checkbox",
        step: 5,
      },
      {
        name: "electricCremationPrice",
        label: "Electric Cremation Price",
        type: "number",
        placeholder: "1500",
        step: 6,
      },
      {
        name: "woodCremationPrice",
        label: "Wood Pyre Cremation Price",
        type: "number",
        placeholder: "5000",
        step: 6,
      },
      {
        name: "platformCharges",
        label: "Platform Rental Charges",
        type: "number",
        placeholder: "500",
        step: 6,
      },
      {
        name: "coldStorageCharges",
        label: "Cold Storage Charges (Per Day)",
        type: "number",
        placeholder: "300",
        step: 6,
      },
      {
        name: "municipalLicense",
        label: "Municipal Corporation License",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 7,
      },
      {
        name: "pollutionCertificate",
        label: "Pollution Control Board Certificate",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 7,
      },
      {
        name: "fireSafety",
        label: "Fire Safety Certificate",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 7,
      },
    ],
  },

  // 6. ANTIM SANSKAR SAMAGRI SHOP
  {
    id: "samagri_supplies",
    name: "pooja Samagri Shop",
    icon: Package,
    fields: [
      {
        name: "shopName",
        label: "Shop Name",
        type: "text",
        placeholder: "Name of your shop",
        required: true,
        step: 2,
      },
      {
        name: "samagriItems",
        label: "Items Available",
        type: "textarea",
        placeholder:
          "Ghee, Camphor, Sandalwood, Incense, Dhoop, Kapur, Agarbatti, Roli, Chandan, Cotton, Mulayam, Phool, Mala, etc.",
        required: true,
        step: 2,
      },
      {
        name: "poojaKits",
        label: "Pooja Kits Available",
        type: "textarea",
        placeholder: "Basic Kit, Premium Kit, Complete Antim Sanskar Kit",
        step: 2,
      },
      {
        name: "specialItems",
        label: "Special Items",
        type: "textarea",
        placeholder: "Panchamrit, Gangajal, Tulsi, Sandalwood paste",
        step: 2,
      },
      {
        name: "basicKitPrice",
        label: "Basic Pooja Kit Price",
        type: "number",
        placeholder: "500",
        step: 3,
      },
      {
        name: "premiumKitPrice",
        label: "Premium Pooja Kit Price",
        type: "number",
        placeholder: "1500",
        step: 3,
      },
      {
        name: "completeKitPrice",
        label: "Complete Antim Sanskar Kit",
        type: "number",
        placeholder: "2500",
        step: 3,
      },
      {
        name: "gheePrice",
        label: "Ghee (Per kg)",
        type: "number",
        placeholder: "400",
        step: 3,
      },
      {
        name: "camphorPrice",
        label: "Camphor (Per pack)",
        type: "number",
        placeholder: "50",
        step: 3,
      },
      {
        name: "sandalwoodPrice",
        label: "Sandalwood (Per 100g)",
        type: "number",
        placeholder: "200",
        step: 3,
      },
      {
        name: "incensePrice",
        label: "Incense Sticks (Per pack)",
        type: "number",
        placeholder: "30",
        step: 3,
      },
      {
        name: "homeDelivery",
        label: "Home Delivery Available",
        type: "checkbox",
        step: 4,
      },
      {
        name: "deliveryArea",
        label: "Delivery Area",
        type: "text",
        placeholder: "Service area",
        step: 4,
      },
      {
        name: "deliveryCharges",
        label: "Delivery Charges",
        type: "number",
        placeholder: "50",
        step: 4,
      },
      {
        name: "minimumOrder",
        label: "Minimum Order Amount",
        type: "number",
        placeholder: "200",
        step: 4,
      },
      {
        name: "openingTime",
        label: "Shop Opening Time",
        type: "time",
        step: 5,
      },
      {
        name: "closingTime",
        label: "Shop Closing Time",
        type: "time",
        step: 5,
      },
      {
        name: "gstCertificate",
        label: "GST Certificate",
        type: "file",
        accept: ".pdf,.jpg,.png",
        step: 6,
      },
      {
        name: "shopLicense",
        label: "Shop & Establishment License",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
    ],
  },

  {
    id: "wood_supply",
    name: "Wood / Lakdi Supplier",
    icon: Flame,
    fields: [
      {
        name: "businessName",
        label: "Business/Firm Name",
        type: "text",
        placeholder: "Wood Supply Co.",
        required: true,
        step: 2,
      },
      {
        name: "woodTypes",
        label: "Wood Types Available",
        type: "textarea",
        placeholder: "Sandalwood, Mango, Neem, Babool, Mixed, Chandan, Gugal",
        required: true,
        step: 2,
      },
      {
        name: "woodQuality",
        label: "Wood Quality",
        type: "select",
        options: ["Premium", "Standard", "Economy", "Mixed"],
        required: true,
        step: 2,
      },
      {
        name: "woodForm",
        label: "Wood Form",
        type: "select",
        options: ["Logs", "Cut Pieces", "Small Sticks", "Mixed"],
        step: 2,
      },
      {
        name: "moistureContent",
        label: "Moisture Content",
        type: "select",
        options: ["Dry (<10%)", "Semi-dry (10-15%)", "Fresh (15-20%)"],
        step: 2,
      },
      {
        name: "stockAvailable",
        label: "Current Stock (kg)",
        type: "number",
        placeholder: "5000",
        required: true,
        step: 3,
      },
      {
        name: "dailySupply",
        label: "Daily Supply Capacity (kg)",
        type: "number",
        placeholder: "1000",
        required: true,
        step: 3,
      },
      {
        name: "sandalwoodPrice",
        label: "Sandalwood (Per kg)",
        type: "number",
        placeholder: "500",
        step: 4,
      },
      {
        name: "mangoWoodPrice",
        label: "Mango Wood (Per kg)",
        type: "number",
        placeholder: "50",
        step: 4,
      },
      {
        name: "neemWoodPrice",
        label: "Neem Wood (Per kg)",
        type: "number",
        placeholder: "40",
        step: 4,
      },
      {
        name: "baboolWoodPrice",
        label: "Babool Wood (Per kg)",
        type: "number",
        placeholder: "45",
        step: 4,
      },
      {
        name: "mixedWoodPrice",
        label: "Mixed Wood (Per kg)",
        type: "number",
        placeholder: "35",
        step: 4,
      },
      {
        name: "gheeWoodPrice",
        label: "Ghee Wood/Sandalwood Mix",
        type: "number",
        placeholder: "600",
        step: 4,
      },
      {
        name: "bulkDiscount",
        label: "Bulk Order Discount (%)",
        type: "number",
        placeholder: "5",
        step: 4,
      },
      {
        name: "deliveryAvailable",
        label: "Delivery Available",
        type: "checkbox",
        step: 5,
      },
      {
        name: "deliveryCharges",
        label: "Delivery Charges",
        type: "number",
        placeholder: "300",
        step: 5,
      },
      {
        name: "freeDeliveryMin",
        label: "Free Delivery Above (kg)",
        type: "number",
        placeholder: "500",
        step: 5,
      },
      {
        name: "serviceArea",
        label: "Delivery Area",
        type: "textarea",
        placeholder: "Areas you serve",
        required: true,
        step: 5,
      },
      {
        name: "timberLicense",
        label: "Timber/Trade License",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
      {
        name: "forestClearance",
        label: "Forest Department Clearance",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
    ],
  },

  // 8. FLOWER & GARLAND SHOP
  {
    id: "flower_garland",
    name: "Flower & Garland Shop",
    icon: Heart,
    fields: [
      {
        name: "shopName",
        label: "Shop Name",
        type: "text",
        placeholder: "Name of flower shop",
        required: true,
        step: 2,
      },
      {
        name: "flowerTypes",
        label: "Flower Types Available",
        type: "textarea",
        placeholder:
          "Marigold (Genda), Rose (Gulab), Jasmine (Mogra), Lotus (Kamal), Tuberose (Rajnigandha), Champa, Parijat, etc.",
        required: true,
        step: 2,
      },
      {
        name: "garlandTypes",
        label: "Garland Types",
        type: "textarea",
        placeholder:
          "Simple Garland, Designer Garland, Premium Garland, Double Mala, Triple Mala",
        step: 2,
      },
      {
        name: "decorationItems",
        label: "Decoration Items",
        type: "textarea",
        placeholder: "Flower petals, Loose flowers, Toran, Flower balls",
        step: 2,
      },
      {
        name: "marigoldGarland",
        label: "Marigold Garland",
        type: "number",
        placeholder: "100",
        step: 3,
      },
      {
        name: "roseGarland",
        label: "Rose Garland",
        type: "number",
        placeholder: "200",
        step: 3,
      },
      {
        name: "mograGarland",
        label: "Mogra Garland",
        type: "number",
        placeholder: "150",
        step: 3,
      },
      {
        name: "mixedGarland",
        label: "Mixed Flower Garland",
        type: "number",
        placeholder: "250",
        step: 3,
      },
      {
        name: "premiumGarland",
        label: "Premium Designer Garland",
        type: "number",
        placeholder: "500",
        step: 3,
      },
      {
        name: "flowerPetal",
        label: "Flower Petals (Per kg)",
        type: "number",
        placeholder: "300",
        step: 3,
      },
      {
        name: "looseFlowerPrice",
        label: "Loose Flowers (Per 100g)",
        type: "number",
        placeholder: "50",
        step: 3,
      },
      {
        name: "homeDelivery",
        label: "Home Delivery Available",
        type: "checkbox",
        step: 4,
      },
      {
        name: "deliveryArea",
        label: "Delivery Area",
        type: "text",
        placeholder: "Service area",
        step: 4,
      },
      {
        name: "deliveryCharges",
        label: "Delivery Charges",
        type: "number",
        placeholder: "50",
        step: 4,
      },
      {
        name: "bulkOrder",
        label: "Bulk Order Available",
        type: "checkbox",
        step: 4,
      },
      {
        name: "decorationService",
        label: "Decoration Service",
        type: "checkbox",
        step: 4,
      },
      {
        name: "shopLicense",
        label: "Shop License",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 5,
      },
    ],
  },

  // 9. TENT & SEATING ARRANGEMENT PROVIDER
  {
    id: "tent_seating",
    name: "Tent & Seating Arrangement",
    icon: Tent,
    fields: [
      {
        name: "businessName",
        label: "Business Name",
        type: "text",
        placeholder: "Tent House Name",
        required: true,
        step: 2,
      },
      {
        name: "tentSizes",
        label: "Tent Sizes Available",
        type: "textarea",
        placeholder: "20x20, 30x30, 40x40, 50x50, 60x60 feet",
        required: true,
        step: 2,
      },
      {
        name: "seatingCapacity",
        label: "Seating Capacity",
        type: "select",
        options: ["100", "200", "300", "500", "1000", "1000+"],
        required: true,
        step: 2,
      },
      {
        name: "chairTypes",
        label: "Chair Types",
        type: "textarea",
        placeholder:
          "Plastic Chairs, Wooden Chairs, Premium Chairs, Banquet Chairs",
        step: 2,
      },
      {
        name: "tableTypes",
        label: "Table Types",
        type: "textarea",
        placeholder: "Plastic Tables, Wooden Tables, Folding Tables",
        step: 2,
      },
      {
        name: "tentTypes",
        label: "Tent Types",
        type: "select",
        options: [
          "Plain Tent",
          "Decorative Tent",
          "Shamiana",
          "AC Tent",
          "PVC Tent",
        ],
        step: 2,
      },
      {
        name: "carpet",
        label: "Carpet/Flooring",
        type: "checkbox",
        step: 3,
      },
      {
        name: "lighting",
        label: "Lighting Decoration",
        type: "checkbox",
        step: 3,
      },
      {
        name: "fans",
        label: "Fans/Coolers",
        type: "checkbox",
        step: 3,
      },
      {
        name: "generator",
        label: "Generator Available",
        type: "checkbox",
        step: 3,
      },
      {
        name: "acUnits",
        label: "AC Units Available",
        type: "checkbox",
        step: 3,
      },
      {
        name: "stageSetup",
        label: "Stage Setup",
        type: "checkbox",
        step: 3,
      },
      {
        name: "soundSystem",
        label: "Sound System",
        type: "checkbox",
        step: 3,
      },
      {
        name: "pandalTheming",
        label: "Pandal Theming/Decoration",
        type: "checkbox",
        step: 3,
      },
      {
        name: "tentRental",
        label: "Tent Rental Charges (Per tent)",
        type: "number",
        placeholder: "5000",
        step: 4,
      },
      {
        name: "chairRental",
        label: "Chair Rental (Per piece)",
        type: "number",
        placeholder: "20",
        step: 4,
      },
      {
        name: "tableRental",
        label: "Table Rental (Per piece)",
        type: "number",
        placeholder: "50",
        step: 4,
      },
      {
        name: "carpetCharges",
        label: "Carpet/Flooring Charges",
        type: "number",
        placeholder: "1000",
        step: 4,
      },
      {
        name: "lightingCharges",
        label: "Lighting Charges",
        type: "number",
        placeholder: "2000",
        step: 4,
      },
      {
        name: "generatorCharges",
        label: "Generator Charges",
        type: "number",
        placeholder: "3000",
        step: 4,
      },
      {
        name: "setupCharges",
        label: "Setup & Removal Charges",
        type: "number",
        placeholder: "2000",
        step: 4,
      },
      {
        name: "deliveryCharges",
        label: "Transport/Delivery Charges",
        type: "number",
        placeholder: "1000",
        step: 4,
      },
      {
        name: "serviceArea",
        label: "Service Area",
        type: "textarea",
        placeholder: "Cities/Areas you serve",
        required: true,
        step: 5,
      },
      {
        name: "advanceBooking",
        label: "Advance Booking Required (Days)",
        type: "number",
        placeholder: "2",
        step: 5,
      },
      {
        name: "securityDeposit",
        label: "Security Deposit",
        type: "number",
        placeholder: "2000",
        step: 5,
      },
      {
        name: "businessLicense",
        label: "Business License",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
      {
        name: "gstCertificate",
        label: "GST Certificate",
        type: "file",
        accept: ".pdf,.jpg,.png",
        step: 6,
      },
    ],
  },

  // 10. BHAJAN MANDALI / PATH GROUP
  {
    id: "bhajan_mandali",
    name: "Bhajan Mandali / Path Group",
    icon: Users,
    fields: [
      {
        name: "groupName",
        label: "Group Name",
        type: "text",
        placeholder: "Name of Bhajan Mandali",
        required: true,
        step: 2,
      },
      {
        name: "memberCount",
        label: "Number of Members",
        type: "number",
        placeholder: "11",
        required: true,
        step: 2,
      },
      {
        name: "bhajanType",
        label: "Bhajan/Path Type",
        type: "textarea",
        placeholder:
          "Ramayan Path, Hanuman Chalisa, Vishnu Sahasranam, Bhajan Kirtan, Sunderkand, Shiv Puran, Bhagwat Katha",
        required: true,
        step: 2,
      },
      {
        name: "leadSinger",
        label: "Lead Singer Name",
        type: "text",
        placeholder: "Name of main artist",
        step: 2,
      },
      {
        name: "groupTradition",
        label: "Group Tradition",
        type: "select",
        options: ["Sanatan", "Arya Samaj", "Vaishnav", "Shaiva", "General"],
        step: 2,
      },
      {
        name: "duration",
        label: "Session Duration",
        type: "select",
        options: [
          "1 Hour",
          "2 Hours",
          "3 Hours",
          "4 Hours",
          "Full Day",
          "Multiple Days",
        ],
        required: true,
        step: 3,
      },
      {
        name: "instruments",
        label: "Instruments Available",
        type: "textarea",
        placeholder:
          "Harmonium, Tabla, Dholak, Manjira, Kartal, Flute, Tanpura",
        step: 3,
      },
      {
        name: "soundSystem",
        label: "Own Sound System",
        type: "checkbox",
        step: 3,
      },
      {
        name: "recordings",
        label: "Previous Recordings Available",
        type: "checkbox",
        step: 3,
      },
      {
        name: "liveStreaming",
        label: "Live Streaming Facility",
        type: "checkbox",
        step: 3,
      },
      {
        name: "basicSession",
        label: "Basic Session Charges",
        type: "number",
        placeholder: "2100",
        step: 4,
      },
      {
        name: "premiumSession",
        label: "Premium Session",
        type: "number",
        placeholder: "5100",
        step: 4,
      },
      {
        name: "fullDayCharges",
        label: "Full Day Charges",
        type: "number",
        placeholder: "11000",
        step: 4,
      },
      {
        name: "multipleDayCharges",
        label: "Multiple Day Package (Per day)",
        type: "number",
        placeholder: "8000",
        step: 4,
      },
      {
        name: "travelCharges",
        label: "Travel Charges",
        type: "number",
        placeholder: "500",
        step: 4,
      },
      {
        name: "serviceArea",
        label: "Service Area",
        type: "textarea",
        placeholder: "Cities/Locations",
        required: true,
        step: 5,
      },
      {
        name: "availability",
        label: "Availability",
        type: "select",
        options: ["Weekends Only", "All Days", "Specific Days"],
        step: 5,
      },
      {
        name: "advanceBooking",
        label: "Advance Booking Required",
        type: "select",
        options: ["1 Day", "3 Days", "1 Week", "2 Weeks"],
        step: 5,
      },
      {
        name: "groupPhoto",
        label: "Group Photo/Video",
        type: "file",
        accept: ".jpg,.png,.mp4",
        step: 6,
      },
    ],
  },

  {
    id: "catering",
    name: "Catering / Brahman Bhoj",
    icon: Utensils,
    fields: [
      {
        name: "businessName",
        label: "Catering Business Name",
        type: "text",
        placeholder: "Name of catering service",
        required: true,
        step: 2,
      },
      {
        name: "menuType",
        label: "Menu Type",
        type: "select",
        options: [
          "Pure Vegetarian",
          "Sattvic (No Onion/Garlic)",
          "Jain",
          "Regular Vegetarian",
          "Vegan",
        ],
        required: true,
        step: 2,
      },
      {
        name: "thaliItems",
        label: "Thali Items",
        type: "textarea",
        placeholder:
          "Rice, Dal, Roti, Sabzi, Papad, Pickle, Salad, Sweets, Buttermilk, etc.",
        required: true,
        step: 2,
      },
      {
        name: "specialDishes",
        label: "Special Dishes",
        type: "textarea",
        placeholder: "Kheer, Puri, Halwa, Pulao, Khichdi",
        step: 2,
      },
      {
        name: "servingCapacity",
        label: "Serving Capacity",
        type: "select",
        options: [
          "Up to 50",
          "Up to 100",
          "Up to 250",
          "Up to 500",
          "Up to 1000",
          "1000+",
        ],
        required: true,
        step: 3,
      },
      {
        name: "servingType",
        label: "Serving Type",
        type: "select",
        options: [
          "Banana Leaf",
          "Steel Thali",
          "Disposable Plates",
          "Arecanut Plates",
          "Premium Thali",
        ],
        step: 3,
      },
      {
        name: "kitchenType",
        label: "Kitchen Type",
        type: "select",
        options: ["Portable Kitchen", "Central Kitchen", "On-site Cooking"],
        step: 3,
      },
      {
        name: "staffCount",
        label: "Number of Staff",
        type: "number",
        placeholder: "10",
        step: 3,
      },
      {
        name: "perPlatePrice",
        label: "Per Plate Price",
        type: "number",
        placeholder: "200",
        required: true,
        step: 4,
      },
      {
        name: "premiumThaliPrice",
        label: "Premium Thali Price",
        type: "number",
        placeholder: "350",
        step: 4,
      },
      {
        name: "minimumOrder",
        label: "Minimum Order (Plates)",
        type: "number",
        placeholder: "50",
        step: 4,
      },
      {
        name: "deliveryCharges",
        label: "Delivery/Setup Charges",
        type: "number",
        placeholder: "1000",
        step: 4,
      },
      {
        name: "bulkDiscount",
        label: "Bulk Order Discount (%)",
        type: "number",
        placeholder: "5",
        step: 4,
      },
      {
        name: "serviceArea",
        label: "Service Area",
        type: "textarea",
        placeholder: "Cities/Areas you serve",
        required: true,
        step: 5,
      },
      {
        name: "advanceBooking",
        label: "Advance Booking Required (Days)",
        type: "number",
        placeholder: "2",
        step: 5,
      },
      {
        name: "foodLicense",
        label: "Food License (FSSAI)",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
      {
        name: "gstCertificate",
        label: "GST Certificate",
        type: "file",
        accept: ".pdf,.jpg,.png",
        step: 6,
      },
      {
        name: "healthCertificate",
        label: "Health/Trade License",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
    ],
  },

  // 12. DOCUMENTATION AGENT (Death Certificate/Hospital Paperwork)
  {
    id: "documentation_help",
    name: "Documentation Agent",
    icon: FileText,
    fields: [
      {
        name: "agentName",
        label: "Agent/Business Name",
        type: "text",
        placeholder: "Name of agency",
        required: true,
        step: 2,
      },
      {
        name: "experience",
        label: "Years of Experience",
        type: "number",
        placeholder: "5",
        required: true,
        step: 2,
      },
      {
        name: "documentServices",
        label: "Documentation Services",
        type: "textarea",
        placeholder:
          "Death Certificate, Birth Certificate, Police NOC, Hospital Formalities, Insurance Claim, Succession Certificate, Legal Heir Certificate",
        required: true,
        step: 2,
      },
      {
        name: "processingTime",
        label: "Average Processing Time",
        type: "select",
        options: [
          "Same Day",
          "Within 24 hrs",
          "Within 48 hrs",
          "Within 3-5 days",
          "Within 1 Week",
        ],
        required: true,
        step: 2,
      },
      {
        name: "municipalAreas",
        label: "Municipal Areas Covered",
        type: "textarea",
        placeholder: "MCGM, Thane MC, Navi Mumbai, Pune, etc.",
        required: true,
        step: 3,
      },
      {
        name: "hospitalCovered",
        label: "Hospitals Covered",
        type: "textarea",
        placeholder: "List of hospitals you work with",
        step: 3,
      },
      {
        name: "policeStations",
        label: "Police Stations Covered",
        type: "textarea",
        placeholder: "List of police stations",
        step: 3,
      },
      {
        name: "homeVisit",
        label: "Home Visit Available",
        type: "checkbox",
        step: 4,
      },
      {
        name: "onlineService",
        label: "Online Documentation Service",
        type: "checkbox",
        step: 4,
      },
      {
        name: "trackingSystem",
        label: "Application Tracking System",
        type: "checkbox",
        step: 4,
      },
      {
        name: "deathCertificate",
        label: "Death Certificate Assistance",
        type: "number",
        placeholder: "500",
        step: 5,
      },
      {
        name: "birthCertificate",
        label: "Birth Certificate Assistance",
        type: "number",
        placeholder: "500",
        step: 5,
      },
      {
        name: "policeNOC",
        label: "Police NOC Assistance",
        type: "number",
        placeholder: "1000",
        step: 5,
      },
      {
        name: "hospitalFormalities",
        label: "Hospital Formalities",
        type: "number",
        placeholder: "500",
        step: 5,
      },
      {
        name: "insuranceClaim",
        label: "Insurance Claim Assistance",
        type: "number",
        placeholder: "2000",
        step: 5,
      },
      {
        name: "legalHeir",
        label: "Legal Heir Certificate",
        type: "number",
        placeholder: "1500",
        step: 5,
      },
      {
        name: "fullPackage",
        label: "Complete Documentation Package",
        type: "number",
        placeholder: "3000",
        step: 5,
      },
      {
        name: "agencyLicense",
        label: "Agency License",
        type: "file",
        accept: ".pdf,.jpg,.png",
        required: true,
        step: 6,
      },
      {
        name: "authorizationLetter",
        label: "Authorization Letter",
        type: "file",
        accept: ".pdf,.jpg,.png",
        step: 6,
      },
    ],
  },

  // Add all remaining categories similarly...
  // Due to length, I'll continue with the rest in a separate response
];

// ============ STEP CONFIGURATION FOR ALL CATEGORIES ============
export const getStepsForCategory = (categoryId: string) => {
  const commonStep = {
    id: 1,
    title: "Personal & Business Info",
    icon: User,
    description: "Your details & documents",
  };

  const category = vendorCategories.find((cat) => cat.id === categoryId);
  const categorySteps = category?.fields || [];
  const maxStep = Math.max(...categorySteps.map((f) => f.step || 2), 2);

  const categorySpecificSteps = [];

  if (categoryId === "pandit_purohit" || categoryId === "priest_shradh") {
    categorySpecificSteps.push(
      {
        id: 2,
        title: "Personal Details",
        icon: User,
        description: "Priest information",
      },
      {
        id: 3,
        title: "Services",
        icon: BookOpen,
        description: "Rituals performed",
      },
      {
        id: 4,
        title: "Availability",
        icon: Clock,
        description: "Service area & time",
      },
      {
        id: 5,
        title: "Charges",
        icon: DollarSign,
        description: "Ceremony fees",
      },
      {
        id: 6,
        title: "Certifications",
        icon: Award,
        description: "Qualifications",
      },
    );
  } else if (
    categoryId === "ambulance_service" ||
    categoryId === "body_transport"
  ) {
    categorySpecificSteps.push(
      {
        id: 2,
        title: "Vehicle Details",
        icon: Truck,
        description: "Vehicle information",
      },
      {
        id: 3,
        title: "Features",
        icon: Shield,
        description: "Vehicle features",
      },
      {
        id: 4,
        title: "Service Details",
        icon: Clock,
        description: "Service area & availability",
      },
      {
        id: 5,
        title: "Pricing",
        icon: DollarSign,
        description: "Charges & rates",
      },
      {
        id: 6,
        title: "Documents",
        icon: FileText,
        description: "Licenses & permits",
      },
    );
  } else if (categoryId === "freezer_box") {
    categorySpecificSteps.push(
      {
        id: 2,
        title: "Inventory",
        icon: Building2,
        description: "Box inventory",
      },
      { id: 3, title: "Features", icon: Shield, description: "Box features" },
      {
        id: 4,
        title: "Pricing",
        icon: DollarSign,
        description: "Rental charges",
      },
      {
        id: 5,
        title: "Services",
        icon: Clock,
        description: "Delivery & service",
      },
      {
        id: 6,
        title: "Availability",
        icon: Calendar,
        description: "Available from",
      },
    );
  } else if (categoryId === "shamshan_ghat") {
    categorySpecificSteps.push(
      {
        id: 2,
        title: "Ghat Details",
        icon: MapPin,
        description: "Crematorium info",
      },
      {
        id: 3,
        title: "Facilities",
        icon: Shield,
        description: "Available facilities",
      },
      {
        id: 4,
        title: "Services",
        icon: Award,
        description: "Additional services",
      },
      {
        id: 5,
        title: "Booking",
        icon: Calendar,
        description: "Booking system",
      },
      {
        id: 6,
        title: "Pricing",
        icon: DollarSign,
        description: "Cremation charges",
      },
      {
        id: 7,
        title: "Licenses",
        icon: FileText,
        description: "Certificates & licenses",
      },
    );
  } else if (
    categoryId === "samagri_supplies" ||
    categoryId === "kafan_arthi" ||
    categoryId === "flower_garland" ||
    categoryId === "wood_supply"
  ) {
    categorySpecificSteps.push(
      {
        id: 2,
        title: "Products",
        icon: Package,
        description: "Product inventory",
      },
      {
        id: 3,
        title: "Pricing",
        icon: DollarSign,
        description: "Product prices",
      },
      {
        id: 4,
        title: "Delivery",
        icon: Truck,
        description: "Delivery service",
      },
      {
        id: 5,
        title: "Business Hours",
        icon: Clock,
        description: "Shop timings",
      },
      { id: 6, title: "Documents", icon: FileText, description: "Licenses" },
    );
  } else if (categoryId === "tent_seating") {
    categorySpecificSteps.push(
      { id: 2, title: "Equipment", icon: Tent, description: "Tent & chairs" },
      {
        id: 3,
        title: "Additional Items",
        icon: Shield,
        description: "Extra facilities",
      },
      {
        id: 4,
        title: "Pricing",
        icon: DollarSign,
        description: "Rental charges",
      },
      {
        id: 5,
        title: "Service Area",
        icon: MapPin,
        description: "Delivery area",
      },
      {
        id: 6,
        title: "Documents",
        icon: FileText,
        description: "Business license",
      },
    );
  } else if (categoryId === "bhajan_mandali") {
    categorySpecificSteps.push(
      {
        id: 2,
        title: "Group Details",
        icon: Users,
        description: "Team information",
      },
      { id: 3, title: "Services", icon: BookOpen, description: "Bhajan types" },
      {
        id: 4,
        title: "Charges",
        icon: DollarSign,
        description: "Service fees",
      },
      {
        id: 5,
        title: "Availability",
        icon: Clock,
        description: "Booking info",
      },
      { id: 6, title: "Portfolio", icon: Camera, description: "Samples" },
    );
  } else if (categoryId === "catering") {
    categorySpecificSteps.push(
      {
        id: 2,
        title: "Menu Details",
        icon: Utensils,
        description: "Food menu",
      },
      {
        id: 3,
        title: "Capacity",
        icon: Users,
        description: "Serving capacity",
      },
      {
        id: 4,
        title: "Pricing",
        icon: DollarSign,
        description: "Per plate charges",
      },
      {
        id: 5,
        title: "Service Area",
        icon: MapPin,
        description: "Delivery area",
      },
      { id: 6, title: "Licenses", icon: FileText, description: "Food license" },
    );
  } else if (
    categoryId === "documentation_help" ||
    categoryId === "death_certificate" ||
    categoryId === "hospital_formalities" ||
    categoryId === "police_noc"
  ) {
    categorySpecificSteps.push(
      {
        id: 2,
        title: "Services",
        icon: FileText,
        description: "Documentation services",
      },
      {
        id: 3,
        title: "Coverage",
        icon: MapPin,
        description: "Service coverage",
      },
      {
        id: 4,
        title: "Processing",
        icon: Clock,
        description: "Processing time",
      },
      {
        id: 5,
        title: "Charges",
        icon: DollarSign,
        description: "Service fees",
      },
      {
        id: 6,
        title: "Documents",
        icon: Shield,
        description: "Agency license",
      },
    );
  } else {
    categorySpecificSteps.push(
      {
        id: 2,
        title: "Service Details",
        icon: Briefcase,
        description: "Your service information",
      },
      {
        id: 3,
        title: "Pricing",
        icon: DollarSign,
        description: "Pricing details",
      },
      {
        id: 4,
        title: "Features",
        icon: Shield,
        description: "Service features",
      },
      {
        id: 5,
        title: "Additional",
        icon: FileText,
        description: "Additional information",
      },
      {
        id: 6,
        title: "Documents",
        icon: FileText,
        description: "Required documents",
      },
    );
  }

  return [commonStep, ...categorySpecificSteps];
};
